import type { TeamId } from './team'

export type TeamInstruction =
  | 'aggressive-batting'
  | 'anchor-batting'
  | 'spin-heavy'
  | 'pace-heavy'
  | 'back-youngsters'
  | 'trust-experience'
  | 'flexible-order'
  | 'fixed-roles'
  | 'defensive'
  | 'high-risk-high-reward'
  | 'balanced'

export interface SeasonSetup {
  userTeam: TeamId
  captainPlayerId: string
  viceCaptainPlayerId: string | null
  instruction: TeamInstruction

  // Opponent setups (generated by LLM persona layer in Phase 2; static in Phase 1)
  opponentSetups: Record<TeamId, OpponentSeasonSetup>
}

export interface OpponentSeasonSetup {
  teamId: TeamId
  captainPlayerId: string
  instruction: TeamInstruction
  llmReasoning: string | null   // null in Phase 1 (no LLM)
}

export interface TeamSeasonResult {
  teamId: TeamId
  wins: number
  losses: number
  noResults: number
  points: number
  nrr: number              // Net Run Rate
  position: number         // 1–10
  qualifiedForPlayoffs: boolean
  seasonStrength: number   // internal computed score
}

export interface AwardWinner {
  playerId: string
  playerName: string
  teamId: TeamId
  value: number            // runs / wickets / composite score
}

export interface SeasonResult {
  year: number
  pointsTable: TeamSeasonResult[]
  playoffTeams: TeamId[]   // top 4
  winner: TeamId
  runnerUp: TeamId
  orangeCap: AwardWinner
  purpleCap: AwardWinner
  mvp: AwardWinner
  bestAuctionBuy: AwardWinner
  worstAuctionBuy: AwardWinner
  teamReviews: Record<TeamId, TeamReview>
}

export interface TeamReview {
  teamId: TeamId
  finalPosition: number
  keyPerformers: string[]       // player names
  underperformers: string[]     // player names
  bestBuy: string | null        // player name
  weakestBuy: string | null     // player name
  squadBalanceRating: number    // 0–10
  battingRating: number         // 0–10
  bowlingRating: number         // 0–10
  depthRating: number           // 0–10
  captaincyImpact: 'positive' | 'neutral' | 'negative'
  auctionValueRating: number    // 0–10
  summary: string               // factual, no advice
}
