import type { TeamId } from './team'

// ── Season simulator new types ──────────────────────────────────────────────

export type TeamPhilosophy =
  | 'power-hitters'
  | 'pace-attack'
  | 'spin-web'
  | 'experience-first'
  | 'youth-revolution'
  | 'balanced'

export type PlayerForm = 'hot' | 'normal' | 'cold' | 'injured'

export type PitchType = 'batting-paradise' | 'pace-friendly' | 'spin-friendly' | 'balanced'

export type BattingStrategy = 'aggressive' | 'anchor-attack' | 'power-surge' | 'flexible'

export type BowlingPlan = 'pace-attack' | 'spin-web' | 'mixed' | 'defensive'

export interface PlayerSeasonStats {
  matches: number
  runs: number
  balls: number
  wickets: number
  catches: number
  fifties: number
  hundreds: number
  fourWicketHauls: number
}

export interface MatchFixture {
  matchIndex: number          // 0-based
  homeTeam: TeamId
  awayTeam: TeamId
  venue: string
  pitchType: PitchType
  result?: MatchResult
}

export interface MatchResult {
  winner: TeamId
  loser: TeamId
  winnerScore: number
  loserScore: number
  winnerWickets: number
  loserWickets: number
  margin: string              // e.g. "24 runs" or "5 wickets"
  playerOfMatch: string       // player name
  commentary?: string         // LLM generated
}

export interface StandingsRow {
  teamId: TeamId
  played: number
  won: number
  lost: number
  noResult: number
  points: number
  nrr: number
  last5: ('W' | 'L' | 'N')[]
  qualifiedForPlayoffs?: boolean
}

export interface PlayerMatchPerformance {
  playerId: string
  runs?: number
  balls?: number
  fours?: number
  sixes?: number
  wickets?: number
  oversBowled?: number
  runsConceded?: number
  catches?: number
  dismissal?: string
}

export interface InningsScore {
  team: TeamId
  runs: number
  wickets: number
  overs: number
  performances: PlayerMatchPerformance[]
}

export interface LiveMatchState {
  fixtureIndex: number
  battingStrategy: BattingStrategy
  bowlingPlan: BowlingPlan
  selectedXI: string[]        // playerIds
  captainId: string
  viceCaptainId: string
  impactPlayerUsed: boolean
  innings1?: InningsScore
  innings2?: InningsScore
  phase: 'pre-match' | 'innings1' | 'innings-break' | 'innings2' | 'result'
}

// ── Existing types below ────────────────────────────────────────────────────

export type TeamInstruction =
  | 'aggressive-batting'
  | 'anchor-batting'
  | 'spin-heavy'
  | 'pace-heavy'
  | 'back-youngsters'
  | 'trust-experience'
  | 'flexible-order'
  | 'fixed-roles'
  | 'defensive'
  | 'high-risk-high-reward'
  | 'balanced'

export interface SeasonSetup {
  userTeam: TeamId
  captainPlayerId: string
  viceCaptainPlayerId: string | null
  instruction: TeamInstruction

  // Opponent setups (generated by LLM persona layer in Phase 2; static in Phase 1)
  opponentSetups: Record<TeamId, OpponentSeasonSetup>
}

export interface OpponentSeasonSetup {
  teamId: TeamId
  captainPlayerId: string
  instruction: TeamInstruction
  llmReasoning: string | null   // null in Phase 1 (no LLM)
}

export interface TeamSeasonResult {
  teamId: TeamId
  wins: number
  losses: number
  noResults: number
  points: number
  nrr: number              // Net Run Rate
  position: number         // 1–10
  qualifiedForPlayoffs: boolean
  seasonStrength: number   // internal computed score
}

export interface AwardWinner {
  playerId: string
  playerName: string
  teamId: TeamId
  value: number            // runs / wickets / composite score
}

export interface SeasonResult {
  year: number
  pointsTable: TeamSeasonResult[]
  playoffTeams: TeamId[]   // top 4
  winner: TeamId
  runnerUp: TeamId
  orangeCap: AwardWinner
  purpleCap: AwardWinner
  mvp: AwardWinner
  bestAuctionBuy: AwardWinner
  worstAuctionBuy: AwardWinner
  teamReviews: Record<TeamId, TeamReview>
}

export interface TeamReview {
  teamId: TeamId
  finalPosition: number
  keyPerformers: string[]       // player names
  underperformers: string[]     // player names
  bestBuy: string | null        // player name
  weakestBuy: string | null     // player name
  squadBalanceRating: number    // 0–10
  battingRating: number         // 0–10
  bowlingRating: number         // 0–10
  depthRating: number           // 0–10
  captaincyImpact: 'positive' | 'neutral' | 'negative'
  auctionValueRating: number    // 0–10
  summary: string               // factual, no advice
}
